# Generated by Django 5.0.3 on 2024-07-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat',
            field=models.TextField(default=''),
        ),
    ]
