# Generated by Django 5.0.3 on 2024-07-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_user_chat_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
